name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Triggers build on pushes to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ hashFiles('package-lock.json') != '' && 'npm' || hashFiles('yarn.lock') != '' && 'yarn' || 'pnpm' }}

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js Static Site
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Next.js exports static sites into this folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
